### ISSUE TITLE
Why is a callback used?

### ISSUE THREAD

**Issue by esco** [zrrrzzt/generate-pincode#1]
Hey there,

I noticed a callback is being used to return a result that was computed synchronously. Was there a specific reason for this?

**Comment by zrrrzzt** [comment]
Stupidity ;-)

No, you're absolutely right. There's no reason for doing the callback pattern in this module. If I decide to redo this module I will change that.

**Comment by zrrrzzt** [comment]
Changed it and pushed v 2.0.1 @esco Thx for your input

**Comment by esco** [comment]
No problem :smile:
